import type { Metadata } from "next";
// Using system fonts locally to avoid remote fetches during build
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SiteHeader } from "@/components/site-header";

// Font variables are defined in globals.css via CSS variables

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-dvh flex flex-col">
            <header className="sticky top-0 z-10 w-full border-b border-black/10 dark:border-white/10 bg-background/80 backdrop-blur supports-[backdrop-filter]:bg-background/60">
              <SiteHeader />
            </header>
            <main className="flex-1 mx-auto max-w-5xl w-full px-4 py-8">{children}</main>
            <footer className="border-t border-black/10 dark:border-white/10 py-6 text-center text-xs text-foreground/70">
              © {new Date().getFullYear()} Tal. All rights reserved.
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
